---
title: The Bookery
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    comments: true
  uploads:
    title: Uploads
    output: true
environment: production
description: 'The Bookery is a large community of over 1000 members focused around
  all things written word. Created in 2020 by Zachary Montgomery and Benjamin Hollon,
  we are dedicated to the creation, consumption, admiration, and discussion of literature. '
baseurl: ''
url: https://bookerycommunity.com
discord_url: tfhg7TW
matomo: false 
show_excerpts: true
header_pages:
- index.md
- friends.md
- events.md
- blog.md
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
